first_django/first_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls'))
]

first_django/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout"),
    path("signup", views.signup_view, name = "signup")
]

first_django/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    
    
    student_id = models.CharField(max_length=10)

first_django/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from .models import User
# Create your views here.

def login_view(request):
    if request.method == "POST":
        # username = print(request.POST["username"])
        # password = print(request.POST["password"])
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증성공")
            login(request, user)
        else:
            print("인증실패")

    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]

        user = User.objects.create_user(username, email, password)
        user.last_name = lastname
        user.first_name = firstname
        user.student_id = student_id
        user.save()
        return redirect("user:login")        
    return render(request, "users/signup.html")

first_django/users/templates/users/login.html
로그인페이지


{% if user.is_authenticated %}
    로그인 성공!!
    {{ user.username }}님 환영합니다.
    <a href="{% url 'user:logout' %}">로그아웃</a>
    {% else %}
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <input name="username" type="text">
        <input name="password" type="password">
        <input type="submit" value="로그인">
    </form>
<a href="{% url 'user:signup' %}">회원가입</a>

{% endif %}

first_django/users/templates/users/signup.html
회원가입 페이지

<br>

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name = "username" type = "text">
    <p>비밀번호</p>
    <input name = "password" type = "password">
    <p>이름</p>
    <input name = "firstname" type = "text">
    <p>성</p>
    <input name = "lastname" type = "text">
    <p>이메일</p>
    <input name = "email" type = "text">
    <p>학번</p>
    <input name = "student_id" type = "text">
    <input type = "submit" value="회원가입">
</form>